# Generated by Django 5.1.6 on 2025-03-06 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('description', models.CharField(default=None, max_length=100)),
                ('serial_number', models.CharField(max_length=13)),
                ('amount_available', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipmentstockitem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
