# Generated by Django 5.1.6 on 2025-03-25 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentstockitem',
            name='rental_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipmentstockitem',
            name='amount_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('quote_number', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('client', models.CharField(max_length=100)),
                ('total_quote_amount', models.PositiveIntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ManyToManyField(to='api.equipmentstockitem')),
            ],
        ),
    ]
