# Generated by Django 4.2.3 on 2023-07-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentstock',
            name='amount',
        ),
        migrations.AddField(
            model_name='equipmentstock',
            name='amount_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipmentstock',
            name='description',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
