# Generated by Django 4.2.3 on 2023-07-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0002_remove_equipmentstock_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentstock',
            name='description',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
